name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: 'Node.Js ${{ matrix.node_version }} on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos

        node_version:
          - 16
          - 18
          - 20
          - latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4.0.3
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          set -xe
          npm i

      - name: Testing
        run: |
          set -xe
          npm run test

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
